#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xxhash
Version  : 2.0.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/6b/64/684870b30b21842618bf3b76378fd32eda944aeb164090746b9a8b70232f/xxhash-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/6b/64/684870b30b21842618bf3b76378fd32eda944aeb164090746b9a8b70232f/xxhash-2.0.0.tar.gz
Summary  : Python binding for xxHash
Group    : Development/Tools
License  : BSD-2-Clause
Requires: xxhash-license = %{version}-%{release}
Requires: xxhash-python = %{version}-%{release}
Requires: xxhash-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=============

%package license
Summary: license components for the xxhash package.
Group: Default

%description license
license components for the xxhash package.


%package python
Summary: python components for the xxhash package.
Group: Default
Requires: xxhash-python3 = %{version}-%{release}

%description python
python components for the xxhash package.


%package python3
Summary: python3 components for the xxhash package.
Group: Default
Requires: python3-core
Provides: pypi(xxhash)

%description python3
python3 components for the xxhash package.


%prep
%setup -q -n xxhash-2.0.0
cd %{_builddir}/xxhash-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596476249
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xxhash
cp %{_builddir}/xxhash-2.0.0/LICENSE %{buildroot}/usr/share/package-licenses/xxhash/a0801f1b6650c5ee6064492efbdd67b47c82f0c6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xxhash/a0801f1b6650c5ee6064492efbdd67b47c82f0c6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
